config/routes.rb
Longitude::Application.routes.draw do
  # named routes
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "documentation" => "statics#documentation", :as => "documentation"


  # REST resources
  resources :users
  resources :sessions

  resources :routes do
    resources :locations, :via => [:get, :post, :delete]
  end

  root :controller => "statics", :action => "start"
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :routes

  attr_accessible :latitude, :longitude

  validates_presence_of :latitude, :longitude, :entity_type, :entity_id
end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :user
  has_many :locations, :as => :entity, :dependent => :destroy

  attr_accessible :name

  # validations
  validates_presence_of :user_id
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password

  # relations
  has_many :routes, :dependent => :destroy

  # validations
  validates_uniqueness_of :email

  attr_accessible :email, :password, :password_confirmation

  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def verify_loged_in
    !!@current_user
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :verify_loged_in

  respond_to :html, :json

  def new
    @route = Route.find params[:route_id]
    @location = Location.new
  end

  def index
    @route = current_user.routes.find params[:route_id]
    @locations = @route.locations

    respond_to do |format|
      format.html
      format.json { render :json => @locations }
    end
  end

  def show
    @route = current_user.routes.find params[:route_id]
    @location = @route.locations.find params[:id]

    respond_to do |format|
      format.html
      format.json { render :json => @location }
    end
  end

  def create
    @route = current_user.routes.find params[:route_id]
    @location = @route.locations.create params[:location]

    flash.alert = "Location '#{@location.latitude}:#{@location.longitude}' on '#{@route.name}' created"
    respond_to do |format|
      format.html { redirect_to edit_route_url(@route) }
      format.json { render :json => @location }
    end
  end

  def destroy
    route = current_user.routes.find params[:route_id]
    location = route.locations.find params[:id]

    flash.alert = "Location deleted." if location.destroy
    respond_to do |format|
      format.html { redirect_to edit_route_url(params[:route_id]) and return }
      format.json { head :ok }
    end
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController

  before_filter :verify_loged_in

  respond_to :html, :json

  def index
    @routes = current_user.routes

    respond_to do |format|
      format.html
      format.json { render :json => @routes }
    end
  end

  def show
    @route = current_user.routes.find params[:id]

    respond_to do |format|
      format.html
      format.json  { render :json => @route}
    end
  end

  def new
    @route = Route.new
  end

  def create
    route = current_user.routes.create params[:route]

    flash.alert = "Route created"
    respond_to do |format|
      format.html { redirect_to :action => :index and return }
      format.json { render :json => route }
    end
  end

  def edit
    @route = Route.find params[:id]
  end

  def update
    new_route_name = params[:route][:name]

    route = current_user.routes.find params[:id]
    route.update_attribute( :name, new_route_name ) if route

    flash.alert = "Route '#{route.name}' updated"
    respond_to do |format|
      format.html { redirect_to :action => :index and return }
      format.json { render json: route }
    end
  end

  def destroy
    route = current_user.routes.find params[:id]
    flash.alert = "Route '#{route.name}' deleted." if route.destroy

    respond_to do |format|
      format.html { redirect_to :action => :index and return }
      format.json { head :ok }
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to controller: :routes, action: :index
    else
      flash.now.alert = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

  def start
  end

  def documentation
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/route_controller_helper.rb
module RouteControllerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag :all %>
  <%= yield :head %>
</head>
<body>

<%= render :partial => "shared/user_nav", :locals => {:current_user => current_user} %>
<%= render :partial => "shared/flash_messages", :locals => {:flash => flash}%>

<%= yield %>

</body>
</html>

app/views/locations/index.html.erb
<% if @route %><h1>Locations for '<%= @route.name %>'</h1><% end %>

<table>
  <% @locations.each do |l| %>
    <tr>
      <td><%= l.latitude %></td>
      <td><%= l.longitude %></td>
    </tr>
  <% end %>
</table>

app/views/locations/new.html.erb
<%= form_tag [@route, @location] do %>
  <%= render :partial => 'shared/form_errors', :locals => { :target => @location } %>
  <p>
    <%= label_tag :latitude %>
    <%= text_field :location, :latitude %>
  </p>
  <p>
    <%= label_tag :longitude %>
    <%= text_field :location, :longitude %>
  </p>
  <p class="button"><%= submit_tag "Add location" %></p>
<% end %>

app/views/locations/show.html.erb
<h1>Location '<%= @location.id %>' for route <%= @route.id %></h1>

<h2>Coordinates</h2>

<p>Latitude: <%= @location.latitude %></p>
<p>Longitude: <%= @location.longitude %></p>

app/views/routes/_locations_table.html.erb
<% if route.locations %>
<table>
  <% route.locations.each do |l|%>
    <tr id="<%= route_url %>">
      <td>
        <%= l.latitude %>
      </td>
      <td>
        <%= l.longitude %>
      </td>
      <td>
        <%= button_to :delete, {:action=>:destroy, :controller=>:locations, :route_id=>route.id, :id=>l.id}, :method => :delete %>
      </td>
    </tr>
  <% end %>
</table>
<% end %>

app/views/routes/edit.html.erb
<h1>Route: <span id="route-name"><%= @route.name %></span></h1>
<h2>Update via http:submit</h2>
<%= form_tag @route, :method => :put do %>
  <p>
    <%= label_tag :name %>
    <%= text_field :route, :name %>
  </p>
  <p class="button"><%= submit_tag "Save" %></p>
<% end %>

<h2>Update via Ajax</h2>
<%= form_tag @route do %>
  <p>
    <%= label_tag :name %>
    <%= text_field :route, :name %>
  </p>
  <p id="ajax-submit" class="button"><%= submit_tag "Save" %></p>
<% end %>

<%= render :partial => 'routes/locations_table', :locals => {:route => @route} %>
<%= link_to 'Add location', new_route_location_url( @route ) %>

<%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>

<%= javascript_tag do %>
$(document).ready(function() {

    $('#ajax-submit').click(function(evt) {
        evt.preventDefault(); evt.stopPropagation();

        $this = $(this);
        $form = $this.parent();
        newName = $form.find('input[type="text"]').val();

        console.log('AUTH_TOKEN:', AUTH_TOKEN);

        $.ajax('<%= route_url %>.json', {
          type: 'PUT',
          data: {
            route: {name: newName}
          },
          success: function(data) {
            console.log('data.name:', data.route.name, 'span:', $('#route-name'));
            $('#route-name').text(data.route.name);
          }
        });

    });
});
<% end %>

app/views/routes/index.html.erb
<h2>Your Routes available:</h2>

<% if @routes %>
  <table>
  <% @routes.each do |route| %>
    <tr>
      <td>
        <%= link_to route.name, route %>
      </td>
      <td>
        <%= button_to :delete, {:action=>:destroy, :controller=>:routes, :id=>route.id}, :confirm => 'Delete: sure?', :method => :delete %>
      </td>
      <td>
        <%= link_to :edit, {:action=>:edit, :controller=>:routes, :id=>route.id} %>
      </td>
    </tr>
  <% end %>
  </table>
<% else %>
  <p>You don't own any routes.</p>
<% end %>
<br />
<br />
<%= link_to "create new route", :controller => :routes, :action => :new %>

app/views/routes/new.html.erb
<%= form_tag :routes do %>
  <%= render :partial => 'shared/form_errors', :locals => { :target => @route } %>
  <p>
    <%= label_tag :name %><br />
    <%= text_field :route, :name %>
  </p>
  <p class="button"><%= submit_tag "Create route" %></p>
<% end %>
<%= link_to 'back', :back %>

app/views/routes/show.html.erb
<% content_for :head do %>
  <title>Longitude - <%= @route.name %> </title>
<% end %>

<h1>Route: <%= @route.name %></h1>

<h2>Locations:</h2>

<%= render :partial => "locations_table", :locals => {:route => @route} %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

app/views/shared/_form_errors.html.erb
<% if target.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% for message in target.errors.full_messages %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_nav.html.erb
<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
   | <%= link_to 'My routes', :controller => :routes, :action => :index %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
   | <%= link_to :home, :root %>
   | <%= link_to :documentation, :documentation %>
</div>

app/views/statics/documentation.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "documentation" %>
<% end %>

<h1>API Documentation</h1>

<h2>Formats</h2>

<p>Valid formats for all resource requests are [ html | json ].</p>

<h2>rake routes</h2>

<h3>Misc.</h3>
<table>
  <thead>
    <tr><th>url name</th> <th>request type</th><th>url</th><th>parameters</th></tr>
  </thead>
  <tbody>
    <tr><td>               root</td> <td>            </td><td>/(.:format)                                    </td><td></td></tr>
    <tr><td>            log_out</td> <td>GET         </td><td>/log_out(.:format)                             </td><td></td></tr>
    <tr><td>            sign_up</td> <td>GET         </td><td>/sign_up(.:format)                             </td><td></td></tr>
    <tr><td>             log_in</td> <td>GET         </td><td>/log_in(.:format)                              </td><td></td></tr>
    <tr><td>      documentation</td> <td>GET         </td><td>/documentation(.:format)                       </td><td></td></tr>
  </tbody>
</table>

<h3>Users</h3>
<table>
  <thead>
    <tr><th>url name</th> <th>request type</th><th>url</th><th>parameters</th></tr>
  </thead>
  <tbody>
    <tr><td>              users</td> <td>GET         </td><td>/users(.:format)                               </td><td></td></tr>
    <tr><td>                   </td> <td>POST        </td><td>/users(.:format)                               </td><td></td></tr>
    <tr><td>           new_user</td> <td>GET         </td><td>/users/new(.:format)                           </td><td></td></tr>
    <tr><td>          edit_user</td> <td>GET         </td><td>/users/:id/edit(.:format)                      </td><td></td></tr>
    <tr><td>               user</td> <td>GET         </td><td>/users/:id(.:format)                           </td><td></td></tr>
    <tr><td>                   </td> <td>PUT         </td><td>/users/:id(.:format)                           </td><td></td></tr>
    <tr><td>                   </td> <td>DELETE      </td><td>/users/:id(.:format)                           </td><td></td></tr>
  </tbody>
</table>

<h3>Sessions</h3>
<table>
  <thead>
    <tr><th>url name</th> <th>request type</th><th>url</th><th>parameters</th></tr>
  </thead>
  <tbody>
    <tr><td>           sessions</td> <td>GET         </td><td>/sessions(.:format)                            </td><td></td></tr>
    <tr><td>                   </td> <td>POST        </td><td>/sessions(.:format)                            </td><td></td></tr>
    <tr><td>        new_session</td> <td>GET         </td><td>/sessions/new(.:format)                        </td><td></td></tr>
    <tr><td>       edit_session</td> <td>GET         </td><td>/sessions/:id/edit(.:format)                   </td><td></td></tr>
    <tr><td>            session</td> <td>GET         </td><td>/sessions/:id(.:format)                        </td><td></td></tr>
    <tr><td>                   </td> <td>PUT         </td><td>/sessions/:id(.:format)                        </td><td></td></tr>
    <tr><td>                   </td> <td>DELETE      </td><td>/sessions/:id(.:format)                        </td><td></td></tr>
  </tbody>
</table>

<h3>Routes &amp; Locations</h3>
<table>
  <thead>
    <tr><th>url name</th> <th>request type</th><th>url</th><th>parameters</th></tr>
  </thead>
  <tbody>
    <tr><td>    route_locations</td> <td>GET         </td><td>/routes/:route_id/locations(.:format)          </td><td></td></tr>
    <tr><td>                   </td> <td>POST        </td><td>/routes/:route_id/locations(.:format)          </td><td></td></tr>
    <tr><td> new_route_location</td> <td>GET         </td><td>/routes/:route_id/locations/new(.:format)      </td><td></td></tr>
    <tr><td>edit_route_location</td> <td>GET         </td><td>/routes/:route_id/locations/:id/edit(.:format) </td><td></td></tr>
    <tr><td>     route_location</td> <td>GET         </td><td>/routes/:route_id/locations/:id(.:format)      </td><td></td></tr>
    <tr><td>                   </td> <td>PUT         </td><td>/routes/:route_id/locations/:id(.:format)      </td><td></td></tr>
    <tr><td>                   </td> <td>DELETE      </td><td>/routes/:route_id/locations/:id(.:format)      </td><td></td></tr>
    <tr><td>                   </td> <td>GET         </td><td>/routes(.:format)                              </td><td></td></tr>
    <tr><td>                   </td> <td>POST        </td><td>/routes(.:format)                              </td><td></td></tr>
    <tr><td>                   </td> <td>GET         </td><td>/routes/new(.:format)                          </td><td></td></tr>
    <tr><td>                   </td> <td>GET         </td><td>/routes/:id/edit(.:format)                     </td><td></td></tr>
    <tr><td>                   </td> <td>GET         </td><td>/routes/:id(.:format)                          </td><td></td></tr>
    <tr><td>                   </td> <td>PUT         </td><td>/routes/:id(.:format)                          </td><td></td></tr>
    <tr><td>                   </td> <td>DELETE      </td><td>/routes/:id(.:format)                          </td><td></td></tr>
  </tbody>
</table>

app/views/statics/start.html.erb
<% content_for :head do %>
  <title>Longitude</title>
<% end %>

<h1>Longitude</h1>

<p>Share your whereabouts.</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <%= render :partial => "shared/form_errors", :locals => {:target => @user} %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>